#default 공통설정
spring:
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_fetch_size: ${chunkSize:100}
        jdbc.batch_size: ${chunkSize:100}

--- # dev 설정
spring:
  config:
    activate:
      on-profile: "dev"

  jpa:
    hibernate:
      ddl-auto: create-drop